import { createHash } from "crypto";
import type { PipelineExpert } from "@/app/types/pipeline";

type ExpertRaw = Omit<PipelineExpert, "resource_id">;

const CURATED: Record<string, ExpertRaw[]> = {
  fitness_weight_loss: [
    {
      name: "Jeff Nippard",
      role: "Strength & Hypertrophy Coach",
      specialty: "Evidence-based training and fat loss",
      bio_snippet: "Natural bodybuilder and science communicator. Publishes peer-reviewed-backed programming.",
      url: "https://jeffnippard.com",
      verified: true,
      tags: ["strength", "fat loss", "evidence-based"],
    },
    {
      name: "Layne Norton (BioLayne)",
      role: "Registered Dietitian & Powerlifter",
      specialty: "Flexible dieting, fat loss without restriction",
      bio_snippet: "PhD in nutritional sciences. Pioneer of IIFYM (flexible dieting). Backed by published research.",
      url: "https://biolayne.com",
      verified: true,
      tags: ["nutrition", "fat loss", "powerlifting"],
    },
    {
      name: "MyFitnessPal",
      role: "Calorie & Macro Tracking App",
      specialty: "Food logging, calorie counting",
      bio_snippet: "The most widely-used free food logging app. Integrates with wearables and most fitness platforms.",
      url: "https://myfitnesspal.com",
      verified: true,
      tags: ["nutrition", "tracking", "app"],
    },
    {
      name: "StrongLifts 5x5",
      role: "Beginner Strength Program",
      specialty: "Compound barbell training for beginners",
      bio_snippet: "Free 3x/week beginner program. Simple, effective, and well-documented.",
      url: "https://stronglifts.com",
      verified: true,
      tags: ["strength", "beginner", "barbell"],
    },
  ],
  real_estate_house_purchase: [
    {
      name: "BiggerPockets",
      role: "Real Estate Education Platform & Community",
      specialty: "First-time buyers, investment properties",
      bio_snippet: "Largest real estate investor community. Free podcasts, forums, calculators, and beginner guides.",
      url: "https://biggerpockets.com",
      verified: true,
      tags: ["real estate", "community", "education"],
    },
    {
      name: "HUD Housing Counselors",
      role: "HUD-Approved Free Counseling",
      specialty: "First-time buyer guidance, foreclosure prevention",
      bio_snippet: "HUD-approved non-profit counselors offer free or low-cost home buying guidance.",
      url: "https://www.hud.gov/findacounselor",
      verified: true,
      tags: ["first-time buyer", "free", "government"],
    },
    {
      name: "Consumer Financial Protection Bureau (CFPB)",
      role: "Mortgage Education Resource",
      specialty: "Understanding mortgages, comparing loan offers",
      bio_snippet: "Government resource with plain-English mortgage guides, loan comparison tools, and complaint filing.",
      url: "https://www.consumerfinance.gov/owning-a-home/",
      verified: true,
      tags: ["mortgage", "government", "education"],
    },
    {
      name: "Redfin",
      role: "Real Estate Marketplace & Buyer's Agent",
      specialty: "Discounted commission rebates to buyers in many markets",
      bio_snippet: "Tech-forward brokerage with market data, neighborhood insights, and lower commission structures.",
      url: "https://redfin.com",
      verified: true,
      tags: ["marketplace", "agent", "data"],
    },
  ],
  entrepreneurship: [
    {
      name: "Y Combinator Startup School",
      role: "Free Startup Accelerator Program",
      specialty: "Early-stage startups: ideation through launch",
      bio_snippet: "Free 10-week online program from the world's top accelerator.",
      url: "https://www.startupschool.org",
      verified: true,
      tags: ["accelerator", "free", "curriculum"],
    },
    {
      name: "Indie Hackers",
      role: "Bootstrapped Founder Community",
      specialty: "Revenue-transparent case studies, founder interviews",
      bio_snippet: "Community of founders building profitable businesses without VC. Real revenue numbers, real stories.",
      url: "https://indiehackers.com",
      verified: true,
      tags: ["bootstrapping", "community", "saas"],
    },
    {
      name: "The Mom Test (Rob Fitzpatrick)",
      role: "Book / Customer Interview Framework",
      specialty: "How to talk to customers without getting lied to",
      bio_snippet: "Essential reading before building anything. Teaches founders how to ask questions that reveal truth.",
      url: "https://momtestbook.com",
      verified: true,
      tags: ["customer development", "book", "validation"],
    },
    {
      name: "Founders Network",
      role: "Peer Mentorship Network for Tech Founders",
      specialty: "Founder-to-founder mentorship, warm intros, executive peer groups",
      bio_snippet: "Vetted community of 600+ tech startup founders. Monthly events, mentorship matching, and investor access.",
      url: "https://foundersnetwork.com",
      verified: true,
      tags: ["network", "mentorship", "community"],
    },
  ],
  athletics: [
    {
      name: "TrainingPeaks",
      role: "Endurance Training Platform",
      specialty: "Structured training plans, coach marketplace, performance tracking",
      bio_snippet: "Used by Olympic athletes and age-groupers alike. Find vetted coaches and follow science-based plans.",
      url: "https://trainingpeaks.com",
      verified: true,
      tags: ["training platform", "endurance", "coaching"],
    },
    {
      name: "NSCA (National Strength & Conditioning Association)",
      role: "Certified Coach Directory",
      specialty: "Strength and conditioning for sport-specific performance",
      bio_snippet: "Find an NSCA-certified strength and conditioning specialist in your area. Gold standard certification.",
      url: "https://www.nsca.com/find-a-professional/",
      verified: true,
      tags: ["strength", "conditioning", "certification"],
    },
    {
      name: "Peter Attia (Drive Podcast)",
      role: "Longevity & Performance Medicine",
      specialty: "Zone 2 training, VO2 max, athletic longevity",
      bio_snippet: "Physician focused on the science of athletic performance and healthspan.",
      url: "https://peterattiamd.com",
      verified: true,
      tags: ["physiology", "longevity", "zone 2"],
    },
    {
      name: "Strava",
      role: "Social Fitness App & Segment Platform",
      specialty: "GPS tracking, segment challenges, community",
      bio_snippet: "Track every workout, compete on local segments, and find training groups. Used by 100M+ athletes globally.",
      url: "https://strava.com",
      verified: true,
      tags: ["tracking", "community", "gps"],
    },
  ],
  creative: [
    {
      name: "Skillshare",
      role: "Online Creative Learning Platform",
      specialty: "Classes in illustration, design, photography, writing, and more",
      bio_snippet: "Thousands of creative classes taught by working professionals. Project-based learning with community feedback.",
      url: "https://skillshare.com",
      verified: true,
      tags: ["classes", "design", "illustration"],
    },
    {
      name: "The Futur (Chris Do)",
      role: "Creative Business Education",
      specialty: "Design thinking, branding, and monetizing creative skills",
      bio_snippet: "Emmy-winning designer teaching creatives how to build sustainable businesses around their craft.",
      url: "https://thefutur.com",
      verified: true,
      tags: ["branding", "business", "design"],
    },
    {
      name: "Behance",
      role: "Creative Portfolio & Discovery Platform",
      specialty: "Showcasing work, finding inspiration, networking with creatives",
      bio_snippet: "Adobe's platform for creatives to showcase portfolios, discover trends, and connect with collaborators worldwide.",
      url: "https://behance.net",
      verified: true,
      tags: ["portfolio", "networking", "inspiration"],
    },
    {
      name: "Austin Kleon",
      role: "Author & Creative Thought Leader",
      specialty: "Creative process, sharing your work, staying inspired",
      bio_snippet: "Author of Steal Like an Artist and Show Your Work. Practical wisdom on the creative life.",
      url: "https://austinkleon.com",
      verified: true,
      tags: ["creativity", "books", "process"],
    },
  ],
  student: [
    {
      name: "Khan Academy",
      role: "Free Online Education Platform",
      specialty: "Math, science, computing, and test prep",
      bio_snippet: "World-class education for anyone, anywhere. Personalized learning with practice exercises and instructional videos.",
      url: "https://khanacademy.org",
      verified: true,
      tags: ["free", "math", "science"],
    },
    {
      name: "Anki",
      role: "Spaced Repetition Flashcard App",
      specialty: "Long-term memorization using scientifically proven spaced repetition",
      bio_snippet: "Free, open-source flashcard app used by medical students and language learners worldwide. Retention rates far exceed traditional study.",
      url: "https://apps.ankiweb.net",
      verified: true,
      tags: ["memorization", "flashcards", "free"],
    },
    {
      name: "Coursera",
      role: "University Course Platform",
      specialty: "Accredited courses from top universities and companies",
      bio_snippet: "Access courses from Stanford, MIT, Google, and more. Earn certificates and degrees online at your own pace.",
      url: "https://coursera.org",
      verified: true,
      tags: ["university", "certificates", "online courses"],
    },
    {
      name: "Ali Abdaal",
      role: "Productivity & Study Coach",
      specialty: "Evidence-based study techniques and productivity systems",
      bio_snippet: "Doctor-turned-educator sharing science-backed study methods. Popularized active recall and spaced repetition techniques.",
      url: "https://aliabdaal.com",
      verified: true,
      tags: ["study tips", "productivity", "evidence-based"],
    },
  ],
  wellness: [
    {
      name: "Huberman Lab (Andrew Huberman)",
      role: "Neuroscientist & Wellness Educator",
      specialty: "Sleep, stress management, nutrition, and brain health",
      bio_snippet: "Stanford neuroscience professor. Translates peer-reviewed research into actionable health protocols.",
      url: "https://hubermanlab.com",
      verified: true,
      tags: ["neuroscience", "sleep", "stress"],
    },
    {
      name: "Headspace",
      role: "Meditation & Mental Health App",
      specialty: "Guided meditation, sleep, and stress reduction",
      bio_snippet: "Approachable meditation for beginners and experienced practitioners. Clinically validated to reduce stress.",
      url: "https://headspace.com",
      verified: true,
      tags: ["meditation", "sleep", "app"],
    },
    {
      name: "Precision Nutrition",
      role: "Nutrition Coaching & Certification",
      specialty: "Habit-based nutrition coaching for sustainable health",
      bio_snippet: "Evidence-based nutrition coaching used by 100K+ clients. Focus on habit change over rigid diets.",
      url: "https://precisionnutrition.com",
      verified: true,
      tags: ["nutrition", "coaching", "habits"],
    },
    {
      name: "Yoga with Adriene",
      role: "Yoga & Movement Instructor",
      specialty: "Free yoga for all levels, mindful movement",
      bio_snippet: "Most-subscribed yoga channel on YouTube. Accessible practices for flexibility, strength, and mental clarity.",
      url: "https://yogawithadriene.com",
      verified: true,
      tags: ["yoga", "free", "mindfulness"],
    },
  ],
  career: [
    {
      name: "LinkedIn Learning",
      role: "Professional Development Platform",
      specialty: "Business, tech, and creative skills courses",
      bio_snippet: "Thousands of expert-led courses with certificates. Integrated with your LinkedIn profile for career visibility.",
      url: "https://linkedin.com/learning",
      verified: true,
      tags: ["professional development", "courses", "certificates"],
    },
    {
      name: "80,000 Hours",
      role: "Career Guidance Non-Profit",
      specialty: "High-impact career planning and research-backed advice",
      bio_snippet: "Oxford-founded non-profit helping people find fulfilling, high-impact careers. Free career guide and 1-on-1 advising.",
      url: "https://80000hours.org",
      verified: true,
      tags: ["career planning", "impact", "free"],
    },
    {
      name: "Glassdoor",
      role: "Company Reviews & Salary Data",
      specialty: "Salary transparency, interview prep, company culture insights",
      bio_snippet: "Millions of company reviews, salary reports, and interview questions shared anonymously by employees.",
      url: "https://glassdoor.com",
      verified: true,
      tags: ["salary", "reviews", "interview prep"],
    },
    {
      name: "Teal",
      role: "AI-Powered Job Search Platform",
      specialty: "Resume building, job tracking, and career growth tools",
      bio_snippet: "Free tools for resume optimization, job application tracking, and LinkedIn profile review. AI-powered career companion.",
      url: "https://tealhq.com",
      verified: true,
      tags: ["resume", "job search", "AI tools"],
    },
  ],
  finance: [
    {
      name: "Investopedia",
      role: "Financial Education Resource",
      specialty: "Investing basics, personal finance, and market analysis",
      bio_snippet: "The most comprehensive free financial education site. Covers everything from budgeting to options trading.",
      url: "https://investopedia.com",
      verified: true,
      tags: ["education", "investing", "free"],
    },
    {
      name: "Bogleheads",
      role: "Index Investing Community",
      specialty: "Low-cost passive investing philosophy",
      bio_snippet: "Community built on John Bogle's principles. Wiki, forums, and guides for simple, effective long-term investing.",
      url: "https://bogleheads.org",
      verified: true,
      tags: ["index funds", "community", "passive investing"],
    },
    {
      name: "You Need A Budget (YNAB)",
      role: "Budgeting App & Methodology",
      specialty: "Zero-based budgeting, debt payoff, saving goals",
      bio_snippet: "Budgeting app with a proven methodology. Average new user saves $600 in the first two months.",
      url: "https://ynab.com",
      verified: true,
      tags: ["budgeting", "app", "debt"],
    },
    {
      name: "The Money Guy Show",
      role: "Personal Finance Educators",
      specialty: "Financial order of operations, wealth building by age",
      bio_snippet: "CFPs breaking down personal finance into actionable steps. Known for their Financial Order of Operations framework.",
      url: "https://moneyguy.com",
      verified: true,
      tags: ["financial planning", "wealth building", "podcast"],
    },
  ],
  language: [
    {
      name: "Anki",
      role: "Spaced Repetition Flashcard App",
      specialty: "Vocabulary retention using scientifically proven spaced repetition",
      bio_snippet: "Free, open-source flashcard app. The gold standard for language learners building long-term vocabulary.",
      url: "https://apps.ankiweb.net",
      verified: true,
      tags: ["vocabulary", "flashcards", "free"],
    },
    {
      name: "iTalki",
      role: "Online Language Tutoring Marketplace",
      specialty: "1-on-1 lessons with native speakers at affordable rates",
      bio_snippet: "Find affordable native-speaker tutors for 150+ languages. Flexible scheduling and conversation practice.",
      url: "https://italki.com",
      verified: true,
      tags: ["tutoring", "native speakers", "conversation"],
    },
    {
      name: "Refold",
      role: "Immersion-Based Language Learning Method",
      specialty: "Comprehensible input, immersion roadmaps",
      bio_snippet: "Free roadmap for learning any language through immersion. Based on Stephen Krashen's input hypothesis.",
      url: "https://refold.la",
      verified: true,
      tags: ["immersion", "method", "free"],
    },
    {
      name: "Pimsleur",
      role: "Audio-Based Language Course",
      specialty: "Speaking and listening through spaced audio repetition",
      bio_snippet: "Audio-first language method trusted for 50+ years. Great for building conversational confidence quickly.",
      url: "https://pimsleur.com",
      verified: true,
      tags: ["audio", "speaking", "conversation"],
    },
  ],
  travel: [
    {
      name: "Rome2Rio",
      role: "Multi-Modal Travel Planner",
      specialty: "Finding routes by plane, train, bus, ferry, and car",
      bio_snippet: "See every way to get between any two points on earth. Compare prices, times, and book directly.",
      url: "https://rome2rio.com",
      verified: true,
      tags: ["routes", "planning", "transport"],
    },
    {
      name: "Nomadic Matt",
      role: "Budget Travel Expert & Author",
      specialty: "Budget travel tips, destination guides, and travel hacking",
      bio_snippet: "New York Times bestselling author. Practical guides for traveling the world on any budget.",
      url: "https://nomadicmatt.com",
      verified: true,
      tags: ["budget", "guides", "tips"],
    },
    {
      name: "Google Flights",
      role: "Flight Search & Price Tracking",
      specialty: "Finding cheap flights, price alerts, flexible date search",
      bio_snippet: "The most powerful free flight search tool. Explore map view, track prices, and find the cheapest dates to fly.",
      url: "https://flights.google.com",
      verified: true,
      tags: ["flights", "deals", "free"],
    },
    {
      name: "Wikivoyage",
      role: "Free Travel Guide",
      specialty: "Community-written destination guides with practical info",
      bio_snippet: "Wikipedia's sister project for travelers. Free, ad-free, and constantly updated by a global community of travelers.",
      url: "https://wikivoyage.org",
      verified: true,
      tags: ["guides", "free", "community"],
    },
  ],
  relationships: [
    {
      name: "The Gottman Institute",
      role: "Relationship Research & Therapy",
      specialty: "Science-based relationship advice and couples therapy",
      bio_snippet: "40+ years of research on what makes relationships succeed. Workshops, books, and therapist directory.",
      url: "https://gottman.com",
      verified: true,
      tags: ["research", "couples", "therapy"],
    },
    {
      name: "Esther Perel",
      role: "Psychotherapist & Relationship Expert",
      specialty: "Modern relationships, communication, and intimacy",
      bio_snippet: "Bestselling author and therapist. Host of Where Should We Begin podcast exploring real couples sessions.",
      url: "https://estherperel.com",
      verified: true,
      tags: ["therapy", "communication", "podcast"],
    },
    {
      name: "Psychology Today Therapist Finder",
      role: "Therapist Directory",
      specialty: "Find licensed therapists, counselors, and support groups nearby",
      bio_snippet: "The largest therapist directory. Filter by specialty, insurance, and approach to find the right fit.",
      url: "https://psychologytoday.com/us/therapists",
      verified: true,
      tags: ["therapy", "directory", "mental health"],
    },
    {
      name: "Nonviolent Communication (Marshall Rosenberg)",
      role: "Communication Framework & Book",
      specialty: "Empathic listening, expressing needs, conflict resolution",
      bio_snippet: "A practical framework for resolving conflicts and deepening connections. Used in relationships, workplaces, and diplomacy.",
      url: "https://nonviolentcommunication.com",
      verified: true,
      tags: ["communication", "conflict resolution", "book"],
    },
  ],
  productivity: [
    {
      name: "Todoist",
      role: "Task Management App",
      specialty: "Task organization, project planning, and habit tracking",
      bio_snippet: "Clean, powerful task manager used by 30M+ people. Natural language input, labels, filters, and integrations.",
      url: "https://todoist.com",
      verified: true,
      tags: ["tasks", "app", "organization"],
    },
    {
      name: "Cal Newport",
      role: "Author & Productivity Researcher",
      specialty: "Deep work, digital minimalism, time-block planning",
      bio_snippet: "Georgetown CS professor and bestselling author. Advocates focused work and intentional technology use.",
      url: "https://calnewport.com",
      verified: true,
      tags: ["deep work", "focus", "books"],
    },
    {
      name: "Notion",
      role: "All-in-One Workspace",
      specialty: "Notes, wikis, project management, and databases",
      bio_snippet: "Flexible workspace combining notes, tasks, and databases. Thousands of free community templates.",
      url: "https://notion.so",
      verified: true,
      tags: ["notes", "workspace", "templates"],
    },
    {
      name: "Tiago Forte (Building a Second Brain)",
      role: "Knowledge Management Expert",
      specialty: "Personal knowledge management and the PARA method",
      bio_snippet: "Creator of the Building a Second Brain methodology. Teaches how to organize digital information for creative output.",
      url: "https://fortelabs.com",
      verified: true,
      tags: ["knowledge management", "PARA", "notes"],
    },
  ],
  mindfulness: [
    {
      name: "Waking Up (Sam Harris)",
      role: "Meditation & Mindfulness App",
      specialty: "Secular meditation, philosophy of mind, daily practice",
      bio_snippet: "Meditation app grounded in neuroscience and contemplative traditions. Free access available for those who can't afford it.",
      url: "https://wakingup.com",
      verified: true,
      tags: ["meditation", "secular", "app"],
    },
    {
      name: "Tara Brach",
      role: "Meditation Teacher & Psychologist",
      specialty: "Mindfulness, self-compassion, and emotional healing",
      bio_snippet: "Clinical psychologist and meditation teacher. Free weekly talks and guided meditations with millions of downloads.",
      url: "https://tarabrach.com",
      verified: true,
      tags: ["meditation", "self-compassion", "free"],
    },
    {
      name: "Insight Timer",
      role: "Free Meditation App & Community",
      specialty: "Guided meditations, timers, live events, teacher community",
      bio_snippet: "World's largest free meditation library. 200K+ guided meditations from 20K+ teachers across traditions.",
      url: "https://insighttimer.com",
      verified: true,
      tags: ["meditation", "free", "community"],
    },
    {
      name: "Thich Nhat Hanh (Plum Village)",
      role: "Zen Master & Mindfulness Tradition",
      specialty: "Applied mindfulness, walking meditation, mindful living",
      bio_snippet: "Teachings from one of the world's most influential mindfulness teachers. Free practices, books, and online retreats.",
      url: "https://plumvillage.org",
      verified: true,
      tags: ["zen", "mindful living", "retreats"],
    },
  ],
  confidence: [
    {
      name: "Brené Brown",
      role: "Researcher & Author",
      specialty: "Vulnerability, courage, shame resilience, and leadership",
      bio_snippet: "Research professor whose TED talk on vulnerability has 60M+ views. Author of Daring Greatly and Atlas of the Heart.",
      url: "https://brenebrown.com",
      verified: true,
      tags: ["vulnerability", "courage", "leadership"],
    },
    {
      name: "Toastmasters International",
      role: "Public Speaking & Leadership Club",
      specialty: "Public speaking practice, leadership development, communication skills",
      bio_snippet: "Non-profit with 16K+ clubs worldwide. Supportive environment to practice speaking and build confidence. Low-cost membership.",
      url: "https://toastmasters.org",
      verified: true,
      tags: ["public speaking", "leadership", "community"],
    },
    {
      name: "BetterHelp",
      role: "Online Therapy Platform",
      specialty: "Licensed therapists for anxiety, self-esteem, and personal growth",
      bio_snippet: "Affordable online therapy with licensed professionals. Chat, phone, and video sessions on your schedule.",
      url: "https://betterhelp.com",
      verified: true,
      tags: ["therapy", "online", "self-esteem"],
    },
    {
      name: "Mark Manson",
      role: "Author & Personal Development Writer",
      specialty: "Self-improvement, values-based living, emotional intelligence",
      bio_snippet: "Author of The Subtle Art of Not Giving a F*ck. No-nonsense advice on building genuine confidence and self-worth.",
      url: "https://markmanson.net",
      verified: true,
      tags: ["self-improvement", "books", "values"],
    },
  ],
};

function makeId(name: string, url: string): string {
  return createHash("sha256")
    .update(name + url)
    .digest("hex")
    .slice(0, 16);
}

export function getCuratedExperts(goalKey: string): PipelineExpert[] {
  const list = CURATED[goalKey] ?? [];
  return list.map((e) => ({
    ...e,
    resource_id: makeId(e.name, e.url),
  }));
}
