import Link from "next/link";

export const metadata = { title: "Terms of Service – Behavio" };

export default function TermsPage() {
  return (
    <div className="min-h-dvh bg-background px-6 py-12">
      <div className="mx-auto max-w-2xl">
        <Link href="/" className="mb-8 inline-block text-sm text-muted-foreground hover:text-foreground">
          ← Back
        </Link>
        <h1 className="mb-2 font-display text-3xl font-bold text-foreground">Terms of Service</h1>
        <p className="mb-8 text-sm text-muted-foreground">Last updated: {new Date().getFullYear()}</p>

        <div className="prose prose-neutral max-w-none space-y-6 text-[15px] leading-relaxed text-foreground">
          <section>
            <h2 className="mb-2 text-lg font-semibold">1. Acceptance</h2>
            <p className="text-muted-foreground">
              By using Behavio, you agree to these terms. If you don't agree, don't use the
              service.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold">2. What Behavio is</h2>
            <p className="text-muted-foreground">
              Behavio is an AI-powered personal coaching and habit-tracking application. It
              generates personalised 90-day plans and daily coaching messages. It is not a
              substitute for professional medical, mental health, or financial advice.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold">3. Your account</h2>
            <p className="text-muted-foreground">
              You are responsible for keeping your account credentials secure. You must be at least
              13 years old to use this service.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold">4. Subscriptions and billing</h2>
            <p className="text-muted-foreground">
              Paid plans are billed monthly or annually via Stripe. You can cancel at any time
              through your account settings. Cancellations take effect at the end of the current
              billing period. No refunds for partial periods unless required by law.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold">5. AI-generated content</h2>
            <p className="text-muted-foreground">
              Coaching plans and messages are generated by AI and may not always be accurate.
              Always use your own judgement. We are not liable for decisions made based on
              AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold">6. Acceptable use</h2>
            <p className="text-muted-foreground">
              You may not misuse the service, attempt to extract data at scale, or use it for any
              unlawful purpose. We reserve the right to suspend accounts that violate these terms.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold">7. Limitation of liability</h2>
            <p className="text-muted-foreground">
              Behavio is provided "as is". To the maximum extent permitted by law, we are not
              liable for any indirect, incidental, or consequential damages arising from use of the
              service.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold">8. Changes</h2>
            <p className="text-muted-foreground">
              We may update these terms. Continued use of the service after changes means you
              accept the new terms.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold">9. Contact</h2>
            <p className="text-muted-foreground">
              Questions?{" "}
              <a href="mailto:hello@trybehavio.com" className="underline hover:text-foreground">
                hello@trybehavio.com
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
